name: eb-denoising
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.12.1
  - appnope=0.1.4
  - asttokens=3.0.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - comm=0.2.3
  - contourpy=1.3.1
  - cycler=0.11.0
  - dav1d=1.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - executing=2.2.1
  - expat=2.7.3
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gettext=0.21.0
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - ipykernel=7.1.0
  - ipython=9.8.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jpeg=9f
  - jupyter_client=8.7.0
  - jupyter_core=5.9.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libavif=1.1.1
  - libcxx=20.1.8
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.84.4
  - libiconv=1.16
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libopenblas=0.3.30
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libsodium=1.0.20
  - libsqlite=3.51.1
  - libtiff=4.7.0
  - libwebp-base=1.3.2
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=2.3.4
  - numpy-base=2.3.4
  - openssl=3.6.0
  - packaging=25.0
  - parso=0.8.5
  - pcre2=10.46
  - pexpect=4.9.0
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.1
  - pot=0.9.6.post1
  - prompt-toolkit=3.0.52
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - pyparsing=3.2.0
  - python=3.11.11
  - python-dateutil=2.9.0post0
  - python_abi=3.11
  - pyzmq=27.1.0
  - readline=8.3
  - scipy=1.16.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.0
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - bokeh==3.8.2
      - cffi==2.0.0
      - clarabel==0.11.1
      - click==8.3.1
      - cloudpickle==3.1.2
      - cvxpy==1.7.5
      - dask==2026.1.2
      - distributed==2026.1.2
      - fsspec==2026.1.0
      - h5py==3.15.1
      - importlib-metadata==8.7.1
      - jinja2==3.1.6
      - joblib==1.5.3
      - locket==1.0.0
      - lz4==4.4.5
      - markupsafe==3.0.3
      - mosek==11.0.30
      - msgpack==1.1.2
      - narwhals==2.15.0
      - npeb==0.1.0
      - osqp==1.0.5
      - pandas==2.3.3
      - partd==1.4.2
      - pyarrow==23.0.0
      - pycparser==2.23
      - pytz==2025.2
      - pyyaml==6.0.3
      - scikit-learn==1.8.0
      - scs==3.2.9
      - sortedcontainers==2.4.0
      - submitit==1.5.4
      - tblib==3.2.2
      - threadpoolctl==3.6.0
      - toolz==1.1.0
      - tzdata==2025.3
      - urllib3==2.6.3
      - xyzservices==2025.11.0
      - zict==3.0.0
      - zipp==3.23.0
prefix: /Users/adway/anaconda3/envs/eb-denoising
