[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "npeb"   # pick a real distribution name; can differ from import name
version = "0.1.0"

[tool.setuptools]
packages = ["npeb"]